trigger: none

pool:
  vmImage: 'macOS-latest'

variables:
  bundleFileLocation: $(Pipeline.Workspace)/bundle/release/app-release.aab
  GoogleJsonApiKeyFile: api-4637160248586217580-429967-5ca1f3964ee4.json
  System.Debug: true
  
pr: none

resources:
  pipelines:
  - pipeline: Solo
    source: kotlin-android-build
    trigger: 
      branches:
        include: 
        - master

stages:
- stage: AppCenter
  jobs:
  - job: Release
    steps:
    - task: DownloadSecureFile@1
      inputs:
        secureFile: '$(GoogleJsonApiKeyFile)'
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        project: 'Gps'
        pipeline: 17
        runVersion: 'latest'
        targetPath: '$(Pipeline.Workspace)'
    # - task: AppCenterDistribute@1
    #   displayName: 'Deploy $(bundleFileLocation) to Visual Studio App Center'
    #   inputs:
    #     serverEndpoint: AppCenter.ms
    #     appSlug: teamwildenberg/SoloMetrics
    #     appFile: '$(bundleFileLocation)'
    #     symbolsIncludeParentDirectory: false
    #     releaseNotesOption: 'input'
    #     releaseNotesInput: 'ddd'
    # - task: GooglePlayRelease@3
    #   inputs:
    #     serviceConnection: 'Google Play Store'
    #     apkFile: '$(bundleFileLocation)'      
    #     track: 'alpha'
    #     languageCode: 'nl-NL'
    #https://medium.com/@andrewleader/publish-android-aab-to-google-play-store-using-azure-devops-pipelines-485683f3b9ec
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'fastlane supply --aab $(bundleFileLocation) --track internal --rollout 1.0 --json_key $(Agent.TempDirectory)/$(GoogleJsonApiKeyFile) --package_name nl.teamwildenberg.SoloMetrics'