name: $(majorVersion).$(minorVersion).$(DOT_BUILD_VERSIONCODE) 

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - kotlin/*

pool:
  vmImage: 'macOS-latest'

variables:
  System.Debug: true
  DOT_KEYSTORE_FILELOCATION: $(Agent.TempDirectory)/keystores.jks
  DOT_KEYSTORE_PASSWORD: $(KeystorePassword)
  DOT_KEYALIAS_PASSWORD: $(KeyAliasPassword)
  majorVersion: 1
  minorVersion: 0
  DOT_BUILD_VERSIONCODE: $[counter(variables['majorVersion'], 2)]
  DOT_BUILD_VERSIONNAME: $(majorVersion).$(minorVersion).$(DOT_BUILD_VERSIONCODE) 


pr: none

stages:
- stage: Build
  jobs:
  - job: Default
    steps:
    - task: replacetokens@3
      inputs:
        targetFiles: 'kotlin/app/build.gradle'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'fail'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'keystores.jks'
    - task: Gradle@2
      inputs:
        workingDirectory: 'kotlin'
        gradleWrapperFile: 'kotlin/gradlew'
        gradleOptions: '-Xmx3072m '
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'bundleRelease'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/kotlin/app/build/outputs/bundle'
        artifact: 'bundle'
        publishLocation: 'pipeline'
