name: $(GitVersion.SemVer)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - kotlin/*

pool:
  vmImage: 'macOS-latest'

variables:
  System.Debug: true
  DOT_KEYSTORE_FILELOCATION: $(Agent.TempDirectory)/solometrics-keystores.jks
  DOT_KEYSTORE_PASSWORD: $(KeystorePassword)
  DOT_KEYALIAS_PASSWORD: $(KeyAliasPassword)
  DOT_BUILD_VERSIONCODE: $[counter()]


pr: none

stages:
- stage: Build
  jobs:
  - job: Versioning
    pool: ubuntu-latest
    steps:
    - task: UseGitVersion@5
      inputs:
        versionSpec: '5.x'
        useConfigFile: true
        configFilePath: './kotlin/gitversion.yml'
      name: GitVersion
    - script: |
        echo "Set replace token variables"
        echo "##vso[task.setvariable variable=DOT_BUILD_VERSIONNAME;isOutput=true]$(GitVersion.MajorMinorPatch) " #The variable DOT_BUILD_VERSIONNAME is set to $(GitVersion.MajorMinorPatch) 
      name: GitVersionPipeline        
  - job: BuildAndTest
    variables:
      DOT_BUILD_VERSIONNAME: $[ stageDependencies.Build.Versioning.outputs['GitVersionPipeline.DOT_BUILD_VERSIONNAME'] ]
    dependsOn: Versioning
    steps:
    - task: replacetokens@3
      inputs:
        targetFiles: 'kotlin/app/build.gradle'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'fail'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
    - task: Gradle@2
      displayName: Build and Unit Test
      inputs:
        workingDirectory: 'kotlin'
        gradleWrapperFile: 'kotlin/gradlew'
        gradleOptions: '-Xmx3072m '
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'assembleDebug'
    - bash: chmod +x kotlin/pipelines/kotlin_integration_test.sh
    - bash: ./kotlin/pipelines/kotlin_integration_test.sh
    # KUDOS
    # https://medium.com/genetec-tech/android-ui-testing-in-azure-devops-81bbe7cea9fd
    - bash: | 
        ./kotlin/gradlew connectedDebugAndroidTest --stacktrace -p ./kotlin
        ./kotlin/gradlew --stop
      displayName: 'Run Instrumented Tests' 
    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFiles: '**/kotlin/app/build/**/TEST*.xml'
        failTaskOnFailedTests: true
        testRunTitle: 'Test results'
      condition: always()
  - job: PackageAndPublish
    variables:
      DOT_BUILD_VERSIONNAME: $[ stageDependencies.Build.Versioning.outputs['GitVersionPipeline.DOT_BUILD_VERSIONNAME'] ]
    dependsOn: BuildAndTest
    steps:
    - task: replacetokens@3
      inputs:
        targetFiles: 'kotlin/app/build.gradle'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'fail'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'solometrics-keystores.jks'
    - task: Gradle@2
      inputs:
        workingDirectory: 'kotlin'
        gradleWrapperFile: 'kotlin/gradlew'
        gradleOptions: '-Xmx3072m '
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'bundleRelease'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/kotlin/app/build/outputs/bundle'
        artifact: 'bundle'
        publishLocation: 'pipeline'
