name: $(GitVersion.SemVer)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - kotlin/*

pool:
  vmImage: 'macOS-latest'

variables:
  System.Debug: true
  DOT_KEYSTORE_FILELOCATION: $(Agent.TempDirectory)/solometrics-keystores.jks
  DOT_KEYSTORE_PASSWORD: $(KeystorePassword)
  DOT_KEYALIAS_PASSWORD: $(KeyAliasPassword)
  DOT_BUILD_VERSIONCODE: $[counter()]
  DOT_BUILD_VERSIONNAME: $(GitVersion.MajorMinorPatch) 


pr: none

stages:
- stage: Build
  jobs:
  - job: Default
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core sdk'
      inputs:
        packageType: sdk
        version: 3.1.100
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: GitVersion@5
      inputs:
        runtime: 'core'
        preferBundledVersion: false
        configFilePath: './kotlin/gitversion.yml'
    - task: replacetokens@3
      inputs:
        targetFiles: 'kotlin/app/build.gradle'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'fail'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'solometrics-keystores.jks'
    - task: Gradle@2
      inputs:
        workingDirectory: 'kotlin'
        gradleWrapperFile: 'kotlin/gradlew'
        gradleOptions: '-Xmx3072m '
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'bundleRelease'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/kotlin/app/build/outputs/bundle'
        artifact: 'bundle'
        publishLocation: 'pipeline'
